version: 1.2
notebooks:
  - name: simple
    format: JUPYTER
    language: PYTHON
    path: /notebook.ipynb
    publish: true
    topic: notebook topic
    authors:
      - name: Author 1
  # - name: invalid
  #   formatadfa: JUPYTER
  #   languageasdfasdf: PYTHON
  #   path: /notebook.ipynb
  #   publish: true
  # - name: invalid name containing spaces
  #   formatadfa: JUPYTER
  #   languageasdfasdf: PYTHON
  #   path: /notebook.ipynb
  #   publish: true
