version: 1.2
notebooks:
  - name: simple
    format: JUPYTER
    language: PYTHON
    path: /notebook.ipynb
    publish: true
  - name: invalid
    formatadfa: JUPYTER
    languageasdfasdf: PYTHON
    path: /notebook.ipynb
    publish: true
