version: 1.2
notebooks:
  - name: simple
    format: JUPYTER
    language: PYTHON
    path: /notebook.ipynb
    publish: true
    topic: simple topic 1 edited from codespace
    authors:
      - name: Another author
    #  - orcid: 0000-0003-1072-5630
  - name: simple2
    format: JUPYTER
    language: PYTHON
    path: /notebook.ipynb
    publish: true
    topic: simple topic 2
    authors:
      - name: SEAB-5999
  - name: simple3
    format: JUPYTER
    language: PYTHON
    path: /notebook.ipynb
    topic: simple topic 3
    authors:
      - name: SEAB-5999
